### ISSUE TITLE
Add publications

### ISSUE THREAD

**Issue by mlinarev** [TheSoftwareDesignLab/thesoftwaredesignlab.github.io#12]
Guys, please include this publications in the TSDL website:

https://www.sciencedirect.com/science/article/pii/S0164121217302807

https://ieeexplore.ieee.org/document/8094467

https://ieeexplore.ieee.org/document/8094439

https://ieeexplore.ieee.org/document/8094446

**Comment by caev03** [comment]
9752474a532467abdb6a40d7d50d3fd5a5c86ad2
