### ISSUE TITLE
Image broken in newsfeed

### ISSUE THREAD

**Issue by mlinarev** [TheSoftwareDesignLab/thesoftwaredesignlab.github.io#18]
<img width="706" alt="Captura de pantalla 2019-04-15 a la(s) 12 42 40 p  m" src="https://user-images.githubusercontent.com/4327882/56153577-269e4200-5f7c-11e9-9964-52230d125569.png">

**Comment by miarevalo10** [comment]
The image was changed to the icsme logo, found in https://conferences.computer.org/icsm/
