### ISSUE TITLE
Align boxes at the bottom (home)

### ISSUE THREAD

**Issue by mlinarev** [TheSoftwareDesignLab/thesoftwaredesignlab.github.io#7]
The boxes are not aligned at the bottom:

![captura de pantalla 2018-09-10 a las 11 13 31](https://user-images.githubusercontent.com/4327882/45309973-a6e25d80-b4ea-11e8-8ef9-a81fd4d87ccb.png)

**Comment by caev03** [comment]
This is how it is going to look in the moment we add another news. I think we can wait to publish the last news we get and the it will look better
![selection_004](https://user-images.githubusercontent.com/5732863/45322575-482edb00-b50e-11e8-818c-43bbcba52632.png)
